### ISSUE TITLE
IPFS Weekly #2 - January 11, 2015

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/roundups#10]

**Comment by eminence** [comment]
Contributors for this period (Mon Jan  4 00:00:00 2016 to Mon Jan 11 00:00:00 2016):
- Andrew Chin
- Christian Couder
- Christian Kniep
- David Dias
- Friedel Ziegelmayer
- Ian Preston
- Jakub (Kubuxu) Sztandera
- Jakub Sztandera
- Jeromy Johnson
- Juan Benet
- Lars Gierth
- Lars-Magnus Skog
- ReadmeCritic
- Richard Littauer
- Stephen Whitmore
- Yuval Langer
- greenkeeperio-bot

**Comment by Kubuxu** [comment]
I am double included, sorry. I've committed once from different computer. Make it only Jakub Sztandera.

**Comment by RichardLitt** [comment]
@Kubuxu no problem. Thanks. :)

**Comment by eminence** [comment]
things to mention (collection of stars from the PM issue)
- (specs) much debate in the IPLD spec about pathing notation.  mildred has done at a lot of work that i think deserves attention
-  IPFS Docker image is now tested automatically on Travis, thanks to ChristianKniep and whyrusleeping, see PR ipfs/go-ipfs#2064 (Docker image volume fix and Sharness tests)
- added - the work-in-progress dev040 migration
- distributions page
- Now you can do npm i -g js-ipfs and use jsipfs bootstrap + id + version commands, fully compatible with go-ipfs repo

**Comment by RichardLitt** [comment]
Posted to IPFS/IPFS.

**Comment by jbenet** [comment]
Published! thanks everyone

**Comment by dignifiedquire** [comment]
![giphy-2](https://cloud.githubusercontent.com/assets/790842/12310394/69e8c23a-ba50-11e5-808c-3bff58997976.gif)

**Comment by RichardLitt** [comment]
More of that please. That is a great gif.

**Comment by dignifiedquire** [comment]
@RichardLitt you have to answer with a gif
![giphy-3](https://cloud.githubusercontent.com/assets/790842/12311234/16a0f146-ba56-11e5-9ba7-f0526f6e84bb.gif)
