### ISSUE TITLE
Idea: Space in IPFS newsletter for open positions for IPFS developers

### ISSUE THREAD

**Issue by momack2** [ipfs/roundups#104]
Hey Newsletter content folks! 

I propose we start including a weekly "IPFS Jobs" section in the IPFS newsletter for any open positions throughout the ecosystem looking for folks with expertise in IPFS or related dweb concepts (kinda like the [rust jobs section of the "this week in rust" newsletter](https://this-week-in-rust.org/blog/2018/11/27/this-week-in-rust-262/#rust-jobs)). I think we'd only want to publish this section if there was a diversity of institutions looking for folks with IPFS skills (aka - we don't want this section to just become a jobs advertising space for one particular company - we want this to be a community resource to help folks with IPFS expertise find opportunities that are great fits for them).

Details needed for each position:
- Title
- Company
- Location (if not distributed)
- Link to job posting

Format:
- [Title at Company, Location](link to job posting)

Of the top of my mind, folks that may be hiring for IPFS/libp2p skills include @MichaelMure @b5 @ianopolous @haadcode @sanderpick @victorb @obo20 @koalalorenzo @steven004

Thoughts? Questions? Other ideas?

**Comment by MichaelMure** [comment]
That would be useful indeed.

**Comment by sanderpick** [comment]
Yes please! Great idea, @momack2

**Comment by momack2** [comment]
Awesome! @renrutnnej - what would be the easiest way to collect submissions for this section each week? I think ideally we'd have a model where folks with open roles only need to update when the role is created and when the role is filled - so maybe something like the way we currently do "upcoming events"?

**Comment by jennwrites** [comment]
@momack2 I think the easiest way would be to email newsletter@ipfs.io or submit via issue or to each week’s PR. This is a great idea, thanks for bringing it up! ☺️

**Comment by momack2** [comment]
First issue went out and worked well. I propose we keep any submitted on
the list for a month by default, and then ping folks to see whether they
are still active or not. For folks that want to add new ones, I just made
comments on the next weeklys PR, which seemed to work well. :)

**Comment by jennwrites** [comment]
We've had a section implemented for well over a month so I'm closing and continuing the practice. ☺️

**Comment by sanderpick** [comment]
Not sure how we missed it, but I should have mentioned we (Textile) filled our role. Thanks again for the help here.

**Comment by jennwrites** [comment]
@sanderpick I can take it off the blog this week. I've been checking the links to make sure they are still active but haven't followed up beyond that, sorry!

**Comment by sanderpick** [comment]
Cool, thank you!
