### ISSUE TITLE
Idea: Move from Tinyletter to MailChimp

### ISSUE THREAD

**Issue by jennwrites** [ipfs/roundups#113]
When I first started doing the IPFS newsletter a year ago, I had discussed moving the content from Tinyletter (which is geared toward plain text) to MailChimp. Tinyletter has been acquired by MailChimp but as far as I know, there’s not a straightforward path to convert a Tinyletter subscription to a MailChimp one.

The reasons for wanting to discuss this move include the ability to track reader data more effectively (Tinyletter only provides subscription numbers, open rates, and unique clicks) and better align the newsletter with the visual presentation of the [IPFS blog](https://blog.ipfs.io/). 

Standardization of the sections and images would help with some of the weird ways Tinyletter has translated spacing, alignment, and hierarchy in the past. 

I've discussed this so far with @momack2 @mikeal but need IT support @jesseclay.

Is there any reason to not move forward with this move?

**Comment by momack2** [comment]
Very supportive! @protocolin / @jesseclay - I believe we already have a MailChimp account we've used in the past, right? Would love to unify if that's easy to get access to the nicer formatting/features Jenn describes!

**Comment by mikeal** [comment]
Considering that Tinyletter is owned by Mailchimp, they’ve done surprisingly little in terms of helping along migration from Tinyletter to Mailchimp. Mailchimp has built integrations for migrating/importing from many services, Tinyletter just isn’t one of them.

We’ll have to use the fallback and get an [export of the contacts from Tinyletter](https://tinyletter.zendesk.com/hc/en-us/articles/360005451694-Exporting-subscribers-in-TinyLetter) to [import into Mailchimp.](https://mailchimp.com/help/import-contacts-mailchimp/)

**Comment by georgeslandry** [comment]
Mailchimp really doesn’t suck. But what issues are you having with tinyletter?

---

**Comment by jennwrites** [comment]
@georgeslandry 
> The reasons for wanting to discuss this move include the ability to track reader data more effectively (Tinyletter only provides subscription numbers, open rates, and unique clicks) and better align the newsletter with the visual presentation of the IPFS blog.

**Comment by georgeslandry** [comment]
Ok well than I guess it’s worth exporting to and from a CSV file in order to make the transition. 

Let me know if you need any help. (I’m sure you don’t). 

---

**Comment by jennwrites** [comment]
Seeing no objections can I get help @jesseclay with getting access to Mailchimp or would it be the same account as Filecoin (which I have access to)?

**Comment by jesseclay** [comment]
@renrutnnej we have a PL & Filecoin Mailchimp, but I'd suggest we create a new MC account for IPFS! You can just go ahead and do this, then please it@protocol.ai to the account as a super admin. Reach out to Phil for billing. Thanks!

**Comment by jennwrites** [comment]
Currently planning to work on this transition during the holiday break between issues (Dec 17-Jan 7)

**Comment by jennwrites** [comment]
Transition complete! Thanks everyone!

I'm keeping my eye on the subscribes in Tinyletter just to make sure that everyone gets ported over, until I stop seeing subscribers in there. AFAIK everything externally should point folks to sign up in MailChimp.
