### ISSUE TITLE
Blog posts for IPFS Camp

### ISSUE THREAD

**Issue by tetrisgm** [ipfs/roundups#115]
Hey @renrutnnej,

I've been reaching out to the various teams at IPFS Camp see if they had some blog posts they did regarding the event. I've got a few here:

Peergos did a follow up to the post that was featured in the weekly newsletter, based on the feature that was spec'ed at the workshop I ran: https://peergos.org/blog#fast_seeking_and_encrypted_history_

Makoto from ENS wrote a few blog posts before and after IPFS Camp:
https://medium.com/the-ethereum-name-service/how-to-enable-eth-domain-in-your-local-network-9ef4c7e01003
https://medium.com/the-ethereum-name-service/how-to-host-your-dapp-with-ipfs-ens-and-access-it-via-ethdns-c96046059d87
https://medium.com/the-ethereum-name-service/towards-interoperable-name-service-standard-9e6c0dd0ee35

Berty is currently writing an article, I'm waiting to hear back from them.

The Gathering wrote two articles: https://medium.com/the-gathering
They're also updating the awesomeipfs coverage.

Hope these are helpful for the newsletter. Can I help in some fashion? Maybe picking quotes, or following up with the teams if you need more details? I can look into pushing these or some new content on the IPFS subreddit too.

**Comment by jennwrites** [comment]
Thanks for the suggestions @leshokunin!

We’ve already covered the Peergos and The Gathering pieces in past issues, but the content by Makoto is new. I'll include that in this week’s issue.

We shared the Berty preview back in early July, but I'll keep an eye out for any blog posts.

As far as help, it’s much easier to add suggestions to the weekly PRs I open for the newsletter, that would be a great help! Thanks again!

**Comment by tetrisgm** [comment]
@renrutnnej any specific things you'd like me to help with in the next newsletters?

**Comment by tetrisgm** [comment]
FYI Berty just replied that they released a new post about IPFS Camp, which you can find here:
https://berty.tech/blog/ipfs-camp/

Hopefully it helps with the next newsletter!

**Comment by jennwrites** [comment]
@leshokunin Thanks! I included it in [this week’s newsletter](https://blog.ipfs.io/weekly-55/) under “IPFS in the wild.”
