### ISSUE TITLE
suggestion: Change "join us on IRC" text to reflect the fact that it's a link to riot.im

### ISSUE THREAD

**Issue by swedneck** [ipfs/roundups#116]
Perhaps it could simply be changed to "Join us on Matrix", or the text could be changed more substantially to advertise the fact that the same chat is available on IRC, Matrix, and Discord, with links to each.

IRC: https://webchat.freenode.net/#ipfs
Discord: https://discord.gg/24fmuwR

For Matrix there are 2 options: 
- Either keep linking to riot.im which is the instance hosted by matrix.org (which is quite overloaded since everyone uses that server)
- Or link to riot.permaweb.io which uses permaweb's server instead, this has way less load and should be noticably faster for users, along with making discovery of other IPFS related rooms easier. Note that this is run by the permaweb team, and mainly admined by me.

**Comment by jennwrites** [comment]
I recently changed the text to say "join us in chat" to not specifically reflect how people choose to connect to matrix, irc, etc.
