### ISSUE TITLE
Q3 IPFS Recap?

### ISSUE THREAD

**Issue by momack2** [ipfs/roundups#124]
Is there a place where we're drafting the Q3 IPFS Ecosystem recap (like [this one from Q2](https://blog.ipfs.io/98-ipfs-weekly-49/))?

**Comment by jennwrites** [comment]
Yes, I am planning on doing this for next week’s newsletter. It just got a little delayed with me being OOO. Will update with link once I get the draft going. Thanks @momack2 ☺️

**Comment by jennwrites** [comment]
Q3 draft started here: https://github.com/ipfs/newsletter/pull/125
