### ISSUE TITLE
Events for

### ISSUE THREAD

**Issue by bmann** [ipfs/roundups#130]
_I'm unclear how to add content to the NEXT edition, 67 on the 12th I guess? So I will add it here -- let me know if / when I can PR additions directly._

---

Fission is running a [series of Decentralized Web Meetups](https://blog.fission.codes/november2019-europe-meetups/). At each, [Brooke @expede](https://github.com/expede) will be doing an IPFS 101 overview, and then explain how we're using it to build the Fission platform. We've got other speakers on other decentralized web topics.

* 15 November 2019 [Berlin, Germany Decentralized Web Meetup](https://ti.to/fission/decentralized-web-meetup-berlin) hosted at the Monadic offices, who will share more on [Radicle](https://radicle.xyx)
* 20 November 2019 [Antwerp, Belgium Decentralized Web Meetup](https://ti.to/fission/decentralized-web-meetup-belgium), where @icidasset will talk about [Diffuse](https://diffuse.sh), his decentralized music player
* 21 November 2019 [Victoria, Canada Tech Meetup](https://ti.to/fission/victoria-tech-meetup-2019), organized with Carson from [Textile](https://textile.io)
* 29 November 2019 [Amsterdam, Netherlands Decentralized Web Meetup](https://ti.to/fission/decentralized-web-meetup-amsterdam), including @berkes presenting peer-to-peer cartography with [Peermaps](https://peermaps.org/)

**Comment by jennwrites** [comment]
@bmann if you add the dates and location I'll make sure it gets in the issue on the 12th. Thanks!

**Comment by bmann** [comment]
@renrutnnej dates and locations are included ^^^ — anything else I need to do?

**Comment by jennwrites** [comment]
Sorry! I misread this. Thanks, I'll make sure it gets in the newsletter right now.

**Comment by jennwrites** [comment]
Events shared as of [weekly #67](https://tinyletter.com/ipfsnewsletter/letters/ipfs-weekly-67). Issues are being looked into concerning the blog but the events were shared widely with the email dispatch on November 12.

**Comment by bmann** [comment]
Thank you!
