### ISSUE TITLE
Submit ideas for end of 2019 recap issue 🎉

### ISSUE THREAD

**Issue by jennwrites** [ipfs/roundups#135]
The end of 2019 is upon us and that means it's time for another year recap issue of the IPFS Weekly! 

Please help me by suggesting milestones, standout contributors, or special memories of the project that should be highlighted in this celebratory issue. 🙏 

This issue will be the first of 2020, distributed Jan 7, 2020!

**Comment by ianopolous** [comment]
Is this meant to be IPFS only or does it include projects in the ipfs ecosystem?

**Comment by jennwrites** [comment]
@ianopolous Great questions! It's meant to be IPFS project-specific, check out [last year’s here](https://blog.ipfs.io/62-ipfs-weekly-24/).

**Comment by ianopolous** [comment]
Conceptually the p2p http proxy developed by Peergos was huge. It enables a seamless and gradual transition from any current architecture to an ipfs based and DNS free architecture for ANY application.

**Comment by vasa-develop** [comment]
A few additions:

- Major go-ipfs, js-ipfs releases. 

- IPFS Cluster added better docs for IPFS Cluster, released major releases(including crdt consensus support) & released js-http-client.

- Filecoin progress, there is a lot to cover here.

- Textile, Peergos, Temporal, Qri, etc. making significant progress.

- ProtoSchool is growing.

- IPFS Camp: Recap: Best camp ever🎉🎉

- We started a couple of projects:
  - [SimpleAsWater](https://simpleaswater.com): An open-source community where anybody can learn and build the stuff on the distributed web. Our aim is to make an incentivized platform for structured content creation(content mostly aiming to give a simple guide to understand DWeb and DWeb projects, and wild practical use-cases in form of tutorials for different DWeb projects).
  - [Dappkit](https://dappkit.io): A Firebase for Web3. We bring the best of the DWeb projects under one roof and help you build scalable dapps with ease(we take care of all the complexities of setting up your infra and user management on our side, while still maintaining the essence of decentralization).

**Comment by jennwrites** [comment]
Shipped: https://mailchi.mp/ipfs/ipfs-in-2019
