### ISSUE TITLE
Ideas needed for Q4 2019 recap

### ISSUE THREAD

**Issue by jennwrites** [ipfs/roundups#137]
We’ll be putting out a Q4 recap as the last issue of 2019, so I need help with your ideas for what to include!

[See the Q3 recap here](https://blog.ipfs.io/weekly-63/).

Previous recaps included:

Quarterly milestones
Videos about IPFS from the quarter
Features in famous publications
Names and number of contributors
New contributors

If you have content you think should be included please share! Thank you!

**Comment by vasa-develop** [comment]
Hi @renrutnnej 

We are still a small project, but maybe you can add [simpleaswater.com](https://simpleaswater.com). 
We are an open-source community where anybody can learn and build the stuff on the distributed web(including content based on Web3 & also build dapps using a "Firebase for Web3" [dappkit.io](https://dappkit.io)).

We launched in Q4, so it's relevant here.

Cheers :)
