### ISSUE TITLE
Cross-posting to the IPFS blog

### ISSUE THREAD

**Issue by jennwrites** [ipfs/roundups#140]
With the move from Tinyletter to Mailchimp, I'm curious to see how people feel about continuing to cross-post the newsletter content to the blog? 

There are integrations out there for rendering Mailchimp to markdown so it should be easy enough, but considering that we're making the move to MC to be able to have better metrics, I am wanting to understand the initial thought process around cross-posting.

**Comment by serejandmyself** [comment]
I think that a lot of people don't really read emails these days, especially news.  This is a lot due to spam filters and the general lack of time. IMHO, it will be awesome if you carry on cross posting the newsletter to the blog too (if I understood the question correctly) =)

**Comment by jennwrites** [comment]
Still cross-posting, so issue is resolved!
