### ISSUE TITLE
Collection for IPFS Weekly 8: March 14th - March 21st

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/roundups#29]
Throw stuff in here!

**Comment by hackergrrl** [comment]
Nothing /done/, but a couple of exciting things in the oven heating up:
- active discussions are happening on a pubsub implementation! (hangout with noffle, jbenet, whyrusleeping, nginnever, haad)
- `ipfs init` for js-ipfs [is almost complete](https://github.com/ipfs/js-ipfs/pull/91)! (/w go-ipfs compatibility)

**Comment by RichardLitt** [comment]
How about: 
- There are some active discussions on PubSub, following a good video chat last week during the hangouts. To join the conversation about the PubSub api, check out this [issue](https://github.com/ipfs/notes/issues/118). 
- @diasdavid organized a research and development meeting for IPFS in Lisbon. If you're in the area, join [this meetup group](http://www.meetup.com/ipfs-lisbon-meetup/events/229530492/) 

I'm not sure that `ipfs init` is worthy, yet! Close though. Can you give me a two sentence description of pubsub?

**Comment by haadcode** [comment]
I'd like to add ipfs-log to the weekly:

https://github.com/haadcode/ipfs-log

> ipfs-log is a partially ordered linked list of IPFS hashes where each entry in the log points to all known heads (a head is a node that is not referenced by other nodes in the log). It can be used as a building block for applications that need to track "dynamic content", eg. track a version of a file, create a feed of IPFS hashes, messaging or as a transport for CRDTs.

**Comment by RichardLitt** [comment]
Thanks! Cool.

**Comment by hackergrrl** [comment]
> Can you give me a two sentence description of pubsub?

What you have works. :+1:

**Comment by lidel** [comment]
There were some changes in [ipfs-firefox-addon](https://github.com/lidel/ipfs-firefox-addon) since it was mentioned in Weekly No.3 (v1.4.2). 

I guess a quick update could look like this:

> The Firefox addon that provides transparent access to IPFS resources via local HTTP2IPFS gateway has been fully reviewed by Mozilla and updated to [v1.5.6](https://addons.mozilla.org/en-US/firefox/addon/ipfs-gateway-redirect/versions/1.5.6).   On average it has [over 350 daily users](https://addons.mozilla.org/en-US/firefox/addon/ipfs-gateway-redirect/statistics/?last=365).
> 
> The 1.5.x series brings various UX improvements such as Realtime Status and Diagnostics, along with experimental features that can be enabled on the Preferences screen.  Check full list [at Github](https://github.com/lidel/ipfs-firefox-addon#features). Feature requests and bug reports [are welcome](https://github.com/lidel/ipfs-firefox-addon/issues)!

**Comment by RichardLitt** [comment]
@lidel Thanks! That's perfect.
