### ISSUE TITLE
Collection for IPFS Weekly #9: March 21-29

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/roundups#31]
Put stuff in here!

@whyrusleeping you gave a talk, I believe?

**Comment by haadcode** [comment]
I've been working on improvements to orbit-db, ipfs-log and Orbit. The message history fetching is
now more stable and the UI feedback for loading messages is fixed. All this work will improve the user experience of Orbit.

**Comment by hackergrrl** [comment]
`js-ipfs init` works! :star2:  I finished the remaining pieces this week, including CLI usage. This included a handful of auxiliary PRs that cascaded out of that work. I've also started a [p2p-handbook](https://github.com/noffle/p2p-handbook/). Lots of thinking and reading about mutable data on IPFS.

**Comment by RichardLitt** [comment]
Nothing to write home about for me this week. But the IPFS Meeting on Wednesday will be my contribution.

**Comment by dignifiedquire** [comment]
I've implemented [dictionary handling](https://github.com/nodeca/pako/pull/77) for pako.js (pure JavaScript port of zlib), to enable full compatibility between Node.js and the brower in [js-libp2p-spdy](https://github.com/diasdavid/js-libp2p-spdy/pull/6).

**Comment by whyrusleeping** [comment]
- I gave a talk at ta3m seattle (video links to come)
- some npm stuff happened and a ton of people started talking about gx, getting close to 1000 stars
- wrote a tool to move content from 0.4.0 to 0.3.11 (https://github.com/whyrusleeping/levart-emit)
- discovered file descriptor leak bug in utp causing connectivity issues
- began work on datastore performance improvements

**Comment by daviddias** [comment]
#### The IPFS Lisbon community group organised the second "Research & Development Meetup"

[The IPFS Lisbon community had their second "Research & Development Meetup"](http://www.meetup.com/ipfs-lisbon-meetup/events/229807984/), hosted by Uniplaces (https://www.uniplaces.com). The focus was "The Distributed Web" and "Machine Learning + Artificial Intelligence for Recommender Algorithms", with talks by [David Dias](https://github.com/diasdavid) and [João Ascensão](https://github.com/jtascensao), respectively. If you are around Lisbon, make sure to join http://www.meetup.com/ipfs-lisbon-meetup to get notified about the next one.
- Good photos: http://ipfs.io/ipfs/Qmd53hsuwkCcrhD1KixBwGMm4tCoLuQvpoW5HWRSqADCrW (feel free to apply filters to improve the colors)
- Slides for The Distributed Web http://www.slideshare.net/DavidDias11/rdm2-the-distributed-web
- Resources - https://github.com/research-development-meetup/discussion/tree/master/rdm-2

**Comment by daviddias** [comment]
Building up on https://github.com/ipfs/weekly/issues/31#issuecomment-202971181 from @dignifiedquire 

#### Dictionary support for the zlib JavaScript Implementation, [`pako`](https://github.com/nodeca/pako)

One of the significant contributions made this week was the addition of 'dictionary' support for `zlib` JavaScript implementation, `pako`. With this contribution, we are able to have a complete implementation of SPDY 3.1's framing layer running in the browser, the default stream muxing library used in IPFS. You can find more about this contribution in the following issue and PR discussions:
- https://github.com/nodeca/pako/issues/69
- https://github.com/diasdavid/js-libp2p-spdy/pull/6
- https://github.com/nodeca/pako/pull/77

**Comment by ghost** [comment]
### DNS outage

We're using DigitalOcean for providing ipfs.io DNS. On Tuesday DigitalOcean DNS was hit by a severe outage lasting hours, which took the public gateway at ipfs.io down. We switched to DNSimple in an ad-hoc fashion and brought ipfs.io back while DigitalOcean was still down, but this incident obviously hit us on the wrong foot a bit. We'll be working to never get taken down this way again. Here's a few things we'll do:
- codified DNS zones, and tools to upload them to DNS providers
- one or two backup DNS providers
- monitoring and failover procedures

We'll post a more detailed postmorten on our blog in the next few days.

### Nginx metrics

Our internal metrics dashboard didn't previously have HTTP request/response metrics from nginx's point of view, but only from IPFS's and multireq's point of view. (Multireq is our v04x/v03x multiplexing proxy). Nginx itself provides finegrained metrics only through their commercial subscriptions. We're now using [mtail](https://github.com/google/mtail) to parse metrics from nginx access logs and expose them to [Prometheus](https://prometheus.io). @lgierth will also contribute the `nginx.mtail` program upstream with mtail.

**Comment by ghost** [comment]
### Meeting with NYC Mesh

@jbenet and @lgierth met with the fine folks of [nycmesh.net](https://nycmesh.net). For the past two years they've been building a community Wifi network in New York City. We had lots of great conversation about wireless mesh networking and IPFS. If you live in NYC, you should come attend their [meetups](http://www.meetup.com/nycmesh/)!

**Comment by ghost** [comment]
The outage thing should probably be placed rather prominently

**Comment by daviddias** [comment]
#### `jsipfs object` cli and http-api endpoints are complete

Now you can use `jsipfs object` in the same way you would use `ipfs object`. Big thanks to [Francisco Dias](https://github.com/xicombd) for leading the last miles of this goal. The complete track of the development can be found at https://github.com/ipfs/js-ipfs/issues/58

**Comment by jbenet** [comment]
Lots of package manager news:
- make a package management section, mention the left-pad problem and why it became a big deal.
- mention that lots of people jumped to ipfs as the solution, and several projects got a lot of attention, and many new ones started. include links to them + a short note?
- http://amreldib.com/blog/HowToUseIpfsToFixNpm
- https://github.com/ipmjs/ipmjs/issues/9
- https://www.npmjs.com/package/cowpen
- david's http://blog.daviddias.me/2015/12/08/stellar-module-management
- https://github.com/whyrusleeping/gx
- https://github.com/mhhf/spore

Discussion on using Bitcoin + IPFS for Decentralized Citizen Journalism: http://thebitcoinnews.com/decentralised-citizen-journalism-we-discuss-the-impact-of-bitcoin-and-ipfs/?utm_source=dlvr.it&utm_medium=twitter

@ christianlundkvist  (Christian Lundkvist) gave a talk on IPFS at http://www.meetup.com/BitDevsNYC/events/229130058/

"IPFS meme of the week" ? 
- https://pbs.twimg.com/media/CePp1CQXEAEJxVa.jpg:large
- from https://twitter.com/jplur_/status/712670265919086594

**Comment by pokeball99** [comment]
https://github.com/hydrusnetwork/hydrus 

"A personal booru-style media tagger that can import files and tags from your hard drive and popular websites. Content can be shared with other users via user-run servers."

Over the last 10 or so updates, the dev of this has been implementing support for ipfs, and now has quick a bit of ipfs related features, which would more than warrant a inclusion in the weekly

(Maybe in the next hour or so I might compile a list what what ipfs related features are in it and update this post, no promises though)

**Comment by RichardLitt** [comment]
@pokeball99 Thanks! I'm going to bundle this into the next newsletter.

**Comment by RichardLitt** [comment]
@pokeball99 Any word on those features?

**Comment by pokeball99** [comment]
@RichardLitt oh yea sorry about that, been bust for the past while, just go though the last 10 or so updates on the releases and that should show you all of the additions

**Comment by RichardLitt** [comment]
@pokeball99 Hmm. On second thought, I'm not sure this warrants inclusion. If you have anything specific you want included that has a relatively high wow factor, pass it on. I'm not sure "x tool now has y amount of IPFS features" is enough, at the moment.

**Comment by RichardLitt** [comment]
Thank you, though!

**Comment by pokeball99** [comment]
@RichardLitt haha, well fair enough, only even bothered mentioning it here due to whyrusleeping saying it was a good idea to
