### ISSUE TITLE
Collection for IPFS Weekly #10: April 6th - April 18th

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/roundups#35]
For this week!

So far, not much!

**Comment by dignifiedquire** [comment]
dignified.js 1.0.0 was released today

**Comment by ianopolous** [comment]
Work on [Peergos](https://github.com/ianopolous/Peergos) is progressing well. We're close to getting a FUSE binding working. Throughput hasn't been as bad as we were expecting with all the encryption and erasure coding, and it's looking likely that it will end up being network IO bound, instead of CPU bound for non trivial writes.

**Comment by RichardLitt** [comment]
0.4.0 release! SpaceX landing!

**Comment by RichardLitt** [comment]
@dignifiedquire: 

> I shipped ipld-cli, ipfs-ipld and ipld updated to the new spec

Care to elaborate? :)

**Comment by dignifiedquire** [comment]
> Care to elaborate? :)

Sure thing:

This week @dignifiedquire shipped an updated version of [js-ipld](https://npmjs.org/ipld) which now conforms to the [latest spec of IPLD](https://github.com/ipfs/specs/tree/master/ipld). In addition [js-ipfs-ipld](https://npmjs.org/ipfs-ipld) was created, which implements the building blocks to use IPLD in js-ipfs. The third package that was published is [js-ipfs-cli](https://npmjs.org/ipld-cli) which gives you a cli tool to interact and experiment with IPLD. 

Screenshot of ipld-cli: http://ipfs.io/ipfs/QmSpMR7kkkzQjov37Nv5xhRRXof7Rnt3Z1TL8G8wjPFbfW

**Comment by RichardLitt** [comment]
Nothing else from why, haad, daviddias.

**Comment by jedahan** [comment]
Made a really rough [first pull request](https://github.com/ipfs/weekly/pull/37), that unfortunately does not incorporate any of the stuff here

**Comment by RichardLitt** [comment]
@jedahan Thanks! Because the previous one never went out, we're likely going to keep working on that one, for now. Hoping to polish it up and look at it in the next couple of hours.

**Comment by RichardLitt** [comment]
@whyrusleeping: we're modularizing go-libp2p, aiming at module parity with js-ipfs. makes the codebase less daunting to newcomers, and making maintenance and testing of everything much easier.

**Comment by RichardLitt** [comment]
@dignifiedquire: `aegir` release. npmjs.org/aegir, github.com/dignifiedquire/aegir

**Comment by RichardLitt** [comment]
@noffle: 

```
#### Readmes

@noffle has started digging hard, to bring the pantheon of js-ipfs modules up to snuff with regards to detailed READMEs with examples and full API notes, as well as 100% test coverage for js-peer-id, js-multiaddr, js-peer-info, and js-ipfs-blocks. There are a lot more modules that still need good READMEs and docs; dive in if you see any!
```

Edit: Use below.

**Comment by daviddias** [comment]
#### `ipfs-blob-store` v1.0.0 released

One of the benefits that comes from the new [Files API](link to best description we have) in 0.4.0, is that we can emulate any kind of file system expectations on top of IPFS, and by doing so, enable applications that use a file system, to use IPFS without any modification. One perfect example of that are all the applications that use a module that implements the [abstract-blob-store](https://github.com/maxogden/abstract-blob-store) interface, now with [ipfs-blob-store](https://github.com/ipfs/ipfs-blob-store), with a simple `npm install`, you can swap out your current blob-store implementation by the IPFS one.

#### `js-ipfs-api` now supports the Files API

On the same lines, `js-ipfs-api` now offers all the Files API calls through a convenient and easy to use library. You can find all of the function declarations on the [`js-ipfs-api` docs](https://github.com/ipfs/js-ipfs-api/blob/master/API.md#files)

**Comment by hackergrrl** [comment]
#### Making js-ipfs and js-libp2p modules awesome

@JGAntunes, @dignifiedquire, @nginnever, @diasdavid, and @noffle have been working hard to bring [the pantheon of js-ipfs modules](https://github.com/ipfs/js-ipfs/issues?utf8=%E2%9C%93&q=is%3Aissue+coverage+dignified) up to snuff: detailed READMEs with examples and full API docs, as well as 100% test coverage. We made significant inroads last sprint on [js-peer-id](https://github.com/diasdavid/js-peer-id), [js-multiaddr](https://github.com/jbenet/js-multiaddr), [js-peer-info](https://github.com/diasdavid/js-peer-info), [js-ipfs-blocks](https://github.com/ipfs/js-ipfs-blocks/) and more! There are a lot more modules that still need good READMEs and docs, so [dive in](https://github.com/ipfs/js-ipfs/issues?utf8=%E2%9C%93&q=is%3Aissue+coverage+dignified+is%3Aopen) and give us a hand!

**Comment by ghost** [comment]
### go-ipfs and the Prometheus monitoring system

We've had [Prometheus](https://prometheus.io) integrated with go-ipfs for some time already. In case you're unfamiliar, Prometheus is an open-source systems monitoring and alerting toolkit. It allows you to monitor diverse services, visualize the collected metrics in dashboards, and define rules for alerting. Together with the Grafana dashboard UI, it's the perfect monitoring system.

The scraping endpoint of go-ipfs is exposed at [:5001/debug/metrics/prometheus](http://localhost:5001/debug/metrics/prometheus) by your go-ipfs daemon. Check Prometheus' [Getting Started guide](https://prometheus.io/docs/introduction/getting_started/) to try it out.

### go-ipfs and restricting dialing

go-ipfs has support for restricting peer connections to certain IP address ranges, by using the `Swarm.AddrFilters` config setting. The following config example illustrates how to exclude all IPv4 peers, and all IPv6 link-local peers.

``` json
// .ipfs/config
"Swarm": {
  "AddrFilters": [
    "/ip4/0.0.0.0/ipcidr/0",
    "/ip6/fe80::/ipcidr/64"
  ]
}
```

### Content-Type of The Week

This week's Content-Type is the non-standard `chemical/x-chemdraw`. ChemDraw is a molecule editor first released in 1985, and still maintained as of today. We don't know which molecules were added to IPFS, but will do our best for IPFS to be around in 30 years just like ChemDraw is still around.

Every week we highlight a Content-Type that we've seen on the public HTTP-to-IPFS gateway at https://ipfs.io. If you're waiting to see one particularly interesting Content-Type in one of the next Weeklies, propose it by `ipfs add -w`'ing a file of that type, and requesting it from the public gateway: https://ipfs.io/ipfs/<hash>

**Comment by RichardLitt** [comment]
Thanks! Added.

**Comment by RichardLitt** [comment]
Closing this one out. Refer to the next collection issue.
