### ISSUE TITLE
Add Newsletter to ipfs.io?

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/roundups#40]
Add to the about page? I've added it in a PR to the community section, but that still seems not as good as it could be.

**Comment by bzz** [comment]
ipfs/website#114

**Comment by jbenet** [comment]
yeah this would be good

**Comment by jbenet** [comment]
i like how hashicorp does it, actually. see the bottom newsletter field in their websites

**Comment by RichardLitt** [comment]
I agree; that is nice.

<img width="1248" alt="screenshot 2016-05-06 16 04 28" src="https://cloud.githubusercontent.com/assets/910753/15084852/3fe4cc92-13a4-11e6-973e-e85a44acc525.png">

**Comment by RichardLitt** [comment]
I believe that this can be closed with the redesign.

**Comment by dignifiedquire** [comment]
I think we still want something like above in the footer in addition to what we have on the website now.

**Comment by daviddias** [comment]
Now it is the perfect timing cause we have the new webpage ready :) Maybe add it below the social icons? 

![image](https://cloud.githubusercontent.com/assets/1211152/16333296/6dc8be56-39f2-11e6-9622-699ffcbcd19c.png)

**Comment by RichardLitt** [comment]
Is there any reason this wasn't done during the new designs?

**Comment by daviddias** [comment]
@RichardLitt it was never mentioned

**Comment by RichardLitt** [comment]
Is it still a priority, then?

**Comment by RichardLitt** [comment]
Reopen as needed.

**Comment by daviddias** [comment]
no more newsletter? :(

**Comment by RichardLitt** [comment]
Not at the moment. If you know of anyone who would like to help me source all of the information for it, then we can start it up again. :)
