### ISSUE TITLE
get_commits.py: Allow unicode characters

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/roundups#49]
I'm having issues with parsing the `Ł` character. 

``` sh
Traceback (most recent call last):
  File "/Users/richard/src/newsletter/tools/get_commits.py", line 110, in <module>
    main(args.repo_dirs, start, end)
  File "/Users/richard/src/newsletter/tools/get_commits.py", line 92, in main
    print "*", a, "https://github.com/ipfs/%s/commit/%s" % author_repo_map[a]
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0141' in position 0: ordinal not in range(128)
```

**Comment by Kubuxu** [comment]
You mean Unicode characters.

**Comment by RichardLitt** [comment]
You're right!

**Comment by RichardLitt** [comment]
Note: this only happens when using `>>` to append to a file, not when it is printed out in the console log.

**Comment by eminence** [comment]
It doesn't make much sense to me that the error would only happen when appending to the file.  The Unicode encoding stuff will happen regardless of where stdout is connected to.   So it seems this error should happen all the time.

I'll take a look

**Comment by RichardLitt** [comment]
That's the only time I saw it. :/

**Comment by RichardLitt** [comment]
You should find the issue if you look through the IPFS repo for this time period: Contributors for this period (2016-07-11T18:02:34 to 2016-07-18T18:02:34). `Łukasz`  throws an error.

**Comment by eminence** [comment]
Reproduced!  I'll check it out

**Comment by eminence** [comment]
Ok, I think this is fixed?  In my local tests this is working properly, so closing this issue.  We can re-open if there are other issues

**Comment by RichardLitt** [comment]
Sounds good. Thanks!
