### ISSUE TITLE
Repo permissions

### ISSUE THREAD

**Issue by ghost** [ipfs/roundups#53]
@RichardLitt you just added me as an individual contributor to this repo -- is there anything that needs to change so we can use teams here too? Individual repo<->contributor relationships get really really messy in a setup as big as hours, spanning multiple orgs, etc.

**Comment by RichardLitt** [comment]
@lgierth Fixed. Added a team; you weren't a team I expected you to be on, but now it should work fine. Reduced individual members to reflect, too.
