### ISSUE TITLE
Email subscriptions

### ISSUE THREAD

**Issue by anacrolix** [ipfs/roundups#68]
Is there a way to receive notifications about new articles by email?

**Comment by mikeal** [comment]
New articles are featured in the weekly newsletter :)

Are you asking about a notification for *only* articles?

**Comment by jennwrites** [comment]
Do you mean IPFS articles, specifically? Would the [blog's RSS feed](https://blog.ipfs.io/index.xml) help give you some sort of notification for what you're looking for?

**Comment by anacrolix** [comment]
All items. RSS is nice, but I don't think many users use it any more, I think we would be missing out on a lot of potential subscribers with only that option. Email subscription seems very common these days.

**Comment by ilyaigpetrov** [comment]
It seems the subscription link was added to the README.md of this repo.
Or am I misunderstand the issue?

**Comment by jennwrites** [comment]
Was this meant to be an issue for https://github.com/ipfs/blog? Will be closing if not responded to by 11/22.

**Comment by anacrolix** [comment]
I don't recall. Are there email subscriptions for the blog?

**Comment by jennwrites** [comment]
Yes, you can subscribe to the blog via RSS here: https://blog.ipfs.io/index.xml
