### ISSUE TITLE
Link to published newsletters

### ISSUE THREAD

**Issue by anacrolix** [ipfs/roundups#69]
There's no link or reference to where the newsletters are published. Presumably https://blog.ipfs.io/ ?

**Comment by jennwrites** [comment]
There's an archive here: https://tinyletter.com/ipfsnewsletter/archive, but since most, if not all of the newsletters get cross posted on the IPFS blog, that's also a good resource.

**Comment by anacrolix** [comment]
Could links to both of these be put on the main page perhaps?

**Comment by anacrolix** [comment]
???

**Comment by jennwrites** [comment]
Sorry, I should clarify. This repo *is* the source for published newsletters, specifically https://github.com/ipfs/newsletter/tree/master/published.
