### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/roundups#7]
Please put IPFS Weekly feedback in here, unless you think something warrants it's own issue! Thanks!

**Comment by NDuma** [comment]
Best overview / update I've seen in my lists so far @RichardLitt (build up of content maybe; but, very comprehensive. https://github.com/ipfs/pm/issues/76 )

I've been searching for tools for user commit tracking [things similar to: http://code.google.com/p/gource | https://github.com/acaudwell/Gource | http://gource.io & https://github.com/rictic/code_swarm | http://www.michaelogawa.com/code_swarm/ ]; I think that this is extremely valuable for attribution & users' internal motivations.
Thanks @eminence for tools/get_commits.py 

Will the "Active Stuff" be expanded and possibly be looking more at something like 'to come' or Next Focus / Coming Priorities?

Would like to follow more from 32c3 more closely; is there more than the image and "Not (Just) Made in China"; is there more content from this event?

Broken Link:
https://github.com/ipfs/registry-mirror

**Comment by jbenet** [comment]
Yeah, excellent update :) :+1:

**Comment by dignifiedquire** [comment]
> Broken Link:
> https://github.com/ipfs/registry-mirror

Correct link: https://github.com/diasdavid/registry-mirror

@diasdavid, maybe move that over to ipfs though?

**Comment by RichardLitt** [comment]
Thanks, @NDuma. I'm not sure if the active stuff will be expanded to "What's to come" - that is a bit harder to estimate, and this is a roundup, not a forecast. The closest thing to that is the weekly sprints, at the moment. 

There isn't more content afaik for 32c3, but you could always talk to the people who were there. 

Fixed the links. Thanks!

**Comment by windemut** [comment]
Is the IPFS Weekly available on IPFS?

**Comment by jbenet** [comment]
@windemut of course. it's on the blog. these are all the same and served through ipfs:
- /ipns/ipfs.io/blog/  <-- in a local gateway.
- https://ipfs.io/ipns/ipfs.io/blog/
- https://ipfs.io/blog/

(yes, even the https://ipfs.io/blog/ is served via ipfs :), using the "dnslink" text record)

**Comment by NDuma** [comment]
#### 32c3 Content:

https://media.ccc.de/c/32c3
via tweets on https://github.com/ipfs/archives/issues/52

##### Add Archive %'s and Completions to Weekly?
- Total Data Stored / Available Space -- Compression Metrics etc?

**Comment by ahoebeke** [comment]
Is it possible to subscribe to the blog? Didn't see any way. Just thinking there's probably a twitter account to follow, but .. which one?

**Comment by hackergrrl** [comment]
There is an [rss feed](http://blog.ipfs.io/rss.xml). The IPFS Twitter account is https://twitter.com/IPFSbot.

**Comment by Kubuxu** [comment]
Also there is https://tinyletter.com/ipfsweekly/

**Comment by NDuma** [comment]
In January I added all repositories here:
https://www.openhub.net/p/ipfs
and included 1 new one within the last 2 days.

I think the metrics & graphs would be a valuable addition.
[Contributors Stats](https://www.openhub.net/p/ipfs/contributors/summary)
[Project Summary](https://www.openhub.net/p/ipfs/commits/summary)
@PeterDP

**Comment by RichardLitt** [comment]
That is actually pretty cool!

**Comment by shazow** [comment]
Really loving the newsletter, thank you for putting it together. :) Not just this week in particular, but every week—one of the few newsletters I look forward to.

One thing I'd love to see in addition: A regular "check in" with important on-going ipfs projects and their status/progress/opportunities to help. Things like ipns, pubsub, etc.

**Comment by RichardLitt** [comment]
Thanks, @shazow! I really appreciate that. 

Check-ins are hard, because we're trying to keep our signal-to-noise ratio optimal, which means not having check ins with all of the dozens (no really, dozens) of projects going on under the IPFS flag. I try to include updates and encourage participation as much as possible, when there is movement on any particular endeavor. If you've got questions about anything, let me know and I can find someone to help you dive in to whichever project you like. :)

**Comment by shazow** [comment]
For sure, I agree it's not reasonable to cover every ipfs project in every newsletter, but a light sampling of "we haven't talked about ipns in a while, and there's no release yet, but here's how progress is going and the big blockers: ..."

**Comment by RichardLitt** [comment]
@shazow I'll work on it! Totally hear you. If you have any suggestions for particular projects, let me know in the future and I'll see if I can add something.

**Comment by Porco-Rosso** [comment]
Just wanted to point out the newsletter link doesn't work!

**Comment by RichardLitt** [comment]
@Porco-Rosso Which one? I changed it recently, may not have gotten them all!

**Comment by Porco-Rosso** [comment]
@RichardLitt 
https://ipfs.io/blog/16-ipfs-weekly-10/ links to https://tinyletter.com/ipfsweekly which gives a 404 error.

I've also checked week 8 and 9 and they all link to the same url that always gives a 404.

**Comment by RichardLitt** [comment]
Thanks! I've raised the issue [here](https://github.com/ipfs/blog/issues/47); for now, use this web address: https://tinyletter.com/ipfsnewsletter. :)

**Comment by RichardLitt** [comment]
Closing. Reopen as needed.
