### ISSUE TITLE
Post Issue #1

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/roundups#9]
Posted! https://github.com/ipfs/ipfs/issues/149

I think we should also send this to the mailing list. I don't think we have one, so I want to set one up at tinyletter.com. I need a good email to send this from - richardlitt@ipfs.io doesn't seem great. What do you guys think?

**Comment by eminence** [comment]
maybe also post to twitter?

**Comment by jbenet** [comment]
Let's post it to the blog, and link that out for the website.

**Comment by dignifiedquire** [comment]
weekly@ipfs.io sounds pretty good to me

**Comment by RichardLitt** [comment]
Posted on the blog. Will work on the email & twitter elsewhere.
