### ISSUE TITLE
Looking for suggestions for Q2 recap issue

### ISSUE THREAD

**Issue by jennwrites** [ipfs/roundups#98]
Hello, just like the end of Q1 2019, I will be putting out a Q2 recap.

[See the Q1 issue here.](https://blog.ipfs.io/79-ipfs-weekly-37/)

Last time I included:

+ Quarterly milestones
+ Videos about IPFS from the quarter
+ Names and number of contributors
+ New contributors
+ Short preview for the rest of 2019

If you have content you think should be included please share! Thank you!

**Comment by terichadbourne** [comment]
Please include the new ProtoSchool tutorial on the Mutable File System (MFS), found at https://proto.school/#/mutable-file-system/ 🎉

**Comment by jennwrites** [comment]
Here’s what I’m working with currently:

# Quarterly milestones

## IPFS contributor office hours call began in May
https://twitter.com/olizilla/status/1125418073689817088

## js-libp2p 0.25.0 released
https://blog.ipfs.io/81-js-libp2p-0-25/

## js-ipfs 0.35.0 and js-ipfs 0.36.0 released
https://blog.ipfs.io/80-js-ipfs-0-35/
https://blog.ipfs.io/89-js-ipfs-0-36/

## go-ipfs 0.4.20 and go-ipfs 0.4.21 released
https://blog.ipfs.io/83-go-ipfs-0-4-20/
https://blog.ipfs.io/93-go-ipfs-0.4.21

## New ProtoSchool tutorial on the Mutable File System (MFS)
https://proto.school/#/mutable-file-system/ 

# We approve this awesome IPFS content

+ [The Complete Beginner's Guide to Deploying Your First Static Website](https://interplanetarygatsby.com/ipfs-deploy/)
+ [IPFS: Technology that’s out of this world](https://business.sprint.com/blog/ipfs-technology/)
+ [How to Host Your Dapp With IPFS+ENS and Access It Via EthDNS](https://medium.com/the-ethereum-name-service/how-to-host-your-dapp-with-ipfs-ens-and-access-it-via-ethdns-c96046059d87)
+ [Continuing to Improve our IPFS Gateway](https://blog.cloudflare.com/continuing-to-improve-our-ipfs-gateway/)
+ [We Made A Dashboard for IPFS Clusters and Now We Want You to Check it Out](https://medium.com/towardsblockchain/we-made-a-dashboard-for-ipfs-clusters-and-now-we-want-you-to-check-it-out-a87234629908)

# Videos about IPFS from the quarter

# Names and number of contributors

# New contributors

# IPFS Camp - More on that soon!
